name: push test2

on:
  push:
    branches: [ "master" ]
    paths:
      - 'test/test2/**'
      - 'test/*'

env:
  test: test-var
  
jobs:
  test:
    name: test2
    runs-on: ubuntu-latest
    steps:
      - name: echo test2 push
        run: |
          echo "push test/test2/**"
