name: push test1

on:
  push:
    branches: [ "master" ]
    paths:
      - 'test/test1/**'
      - 'test/common/**'

env:
  test: test-var
  
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: echo test1 push
        run: |
          echo "github : ${{github}}"
          echo "push test/test1/**"
