name: push test1

on:
  push:
    branches: [ "master" ]
    paths:
      - 'test/test1/**'
      - 'test/common/**'

env:
  test: test-var
  
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: echo test1 push
        run: |
          echo "github.ref : ${{github.ref}}"
          echo "github.path : ${{github.path}}"
          echo "github.event_path : ${{github.event_path}}"
          echo "github.ref_name : ${{github.ref_name}}"
          echo "github.ref_type : ${{github.ref_type}}"
          echo "push test/test1/**"
