name: push test

on:
  push:
    branches: [ "no" ]

env:
  test: test-var
  
jobs:
  test:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: |
          echo "env test : $test"
          
